FROM ubuntu:16.04

# Tested with openfst version 1.6.1
ARG OPENFST_VERSION=1.6.7
ARG NUM_BUILD_CORES=8
ARG INSTALL_IN_CONTAINER=no
ENV OPENFST_VERSION ${OPENFST_VERSION}
ENV NUM_BUILD_CORES ${NUM_BUILD_CORES}
ENV INSTALL_IN_CONTAINER ${INSTALL_IN_CONTAINER}

RUN ln -s -f bash /bin/sh
RUN apt-get update
RUN apt-get install -y wget make gcc g++ checkinstall python-dev libz-dev

RUN wget http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-${OPENFST_VERSION}.tar.gz
RUN tar -xvf openfst-${OPENFST_VERSION}.tar.gz -C /
RUN mkdir -p /openfst-deb

WORKDIR /openfst-${OPENFST_VERSION}
RUN ./configure \
        --enable-static=yes \
        --enable-shared=no \
        --with-pic=yes \
        --enable-far \
        --enable-python
RUN make 
RUN make install
#RUN checkinstall -Dy --install=${INSTALL_IN_CONTAINER}
#RUN mv openfst_${OPENFST_VERSION}-1_amd64.deb /openfst-deb
#VOLUME /openfst-deb

RUN DEBIAN_FRONTEND=noninteractive && \
        apt-get update && \
        apt-get install -y \
                gcc g++ gfortran \
                libc++-dev \
                libstdc++6-4.7-dev zlib1g-dev \
                automake autoconf libtool \
                git subversion \
                libatlas3-base \
                ffmpeg \
                python3 python3-dev python3-pip \
                python python-dev python-pip \
                wget unzip


#RUN apt-get install openfst
COPY ./gentle /gentle
RUN export MAKEFLAGS=' -j8' &&  cd /gentle/ext && \
       /gentle/ext/kaldi/tools/extras/install_mkl.sh && apt-get install sox -y && ./install_kaldi.sh && \
       make depend && make && rm -rf kaldi *.o



ADD . /gentle
RUN cd /gentle && python3 setup.py develop
RUN cd /gentle && ./install_models.sh


ENTRYPOINT ["/bin/bash"]
